/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/AccountHeader`; params?: Router.UnknownInputParams; } | { pathname: `/components/ActionButtons`; params?: Router.UnknownInputParams; } | { pathname: `/components/BalanceDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomTabBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/CryptoAsset`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WalletScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AccountHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ActionButtons`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BalanceDisplay`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BottomTabBar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CryptoAsset`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/WalletScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/AccountHeader${`?${string}` | `#${string}` | ''}` | `/components/ActionButtons${`?${string}` | `#${string}` | ''}` | `/components/BalanceDisplay${`?${string}` | `#${string}` | ''}` | `/components/BottomTabBar${`?${string}` | `#${string}` | ''}` | `/components/CryptoAsset${`?${string}` | `#${string}` | ''}` | `/screens/WalletScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/AccountHeader`; params?: Router.UnknownInputParams; } | { pathname: `/components/ActionButtons`; params?: Router.UnknownInputParams; } | { pathname: `/components/BalanceDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomTabBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/CryptoAsset`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WalletScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
